DROP TABLE IF EXISTS check_ledger;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS analysis_results;
DROP TABLE IF EXISTS document_sources;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS pgcrypto;
